### ISSUE TITLE
no Own Cloud

### ISSUE THREAD

**Issue by ghost** [eon01/OwnCloud_Vagrant_SaltStack#1]
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.
xxxx@xxxxx ~/vagrant/owncloud_vagrant_saltstack $

http://127.0.0.1/owncloud

Unable to connect

Firefox can't establish a connection to the server at 127.0.0.1.

The site could be temporarily unavailable or too busy. Try again in a few moments.
If you are unable to load any pages, check your computer's network connection.
If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by ghost** [comment]
Is the solution in the ebook?

**Comment by eon01** [comment]
@froottools You should try this URL instead:

 http://127.0.0.1:4567/owncloud/

I will update the README file since I forgot to mention the port forwarding.
